#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a basic HTML page with the required content
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Ensure ownership and permission for file
sudo chown www-data:www-data /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html

# Restart nginx
sudo /etc/init.d/nginx restart
