#!/usr/bin/env bash
# Check if Nginx is installed
if [ ! -x "$(command -v nginx)" ]; then
    # Install Nginx if not installed
    sudo apt-get -y update
    sudo apt-get -y install nginx
fi

# Create a configuration file for the redirection
echo "server {
    listen 80;
    server_name _;
    add_header X-Served-By $HOSTNAME;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo /etc/init.d/nginx restart
