#!usr/bin/env bash

# Check if Nginx is installed
if [ ! -x "$(command -v nginx)" ]; then
    # Install Nginx if not installed
    sudo apt-get -y update
    sudo apt-get -y install nginx
fi

# Create a configuration file for the custom 404 page
echo "server {
    listen 80;
    server_name _;
    add_header X-Served-By $HOSTNAME;
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/custom_404 > /dev/null

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html > /dev/null

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo /etc/init.d/nginx restart
